name: MunchausenFireworks
main: me.fromgate.munchausen.Munchausen
version: 0.5.0
website: http://fromgate.me
author: fromgate, fromgate@gmail.com
commands:
   munchausen:
      aliases: [mfirework,munch]
      description: Munchausen Fireworks command
      usage: |
           /munchausen help